### ISSUE TITLE
Series_release KeyError

### ISSUE THREAD

**Issue by JakubIg** [TomasKoutek/pystlouisfed#1]
Hello Tomas,
I have recently discovered your package and I really enjoy using it. However, I spotted one minor error, which source I have already found. During usage of series_release method of Client class, I got following error: 

>   File "C:\Users\jignatik001\AppData\Local\Temp\ipykernel_16792\281466159.py", line 4, in <module>
>     fred.series_release('T10Y2YM')
> 
>   File "C:\Users\jignatik001\Anaconda3\lib\site-packages\pystlouisfed\client.py", line 2248, in series_release
>     df = df.astype(dtype={
> 
>   File "C:\Users\jignatik001\Anaconda3\lib\site-packages\pandas\core\generic.py", line 5879, in astype
>     raise KeyError(
> 
> KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'link' not found in columns."

When we look at the XML tree of request (https://api.stlouisfed.org/fred/series/release?series_id=T10Y2YM&api_key=abcdefghijklmnopqrstuvwxyz123456), we can notice that there is no link associated with the release of our series. However, in following fragment of series_release method, we try to convert unexisting link to string, what causes an error:

```
df = df.astype(dtype={
                'name': 'string',
                'link': 'string',
                'press_release': 'bool'
            }).set_index('id')
```

Thanks in advance for your help!

**Comment by TomasKoutek** [comment]
Hi Jakub,
I apologize for the late response. I didn't believe anyone was using this package :-).
Thanks for the issue, I fixed the behavior in version 2.1.1 (https://github.com/TomasKoutek/pystlouisfed/commit/bbc35f71d4283da33cec556829cfdb50b12a5315).
If you have any other bugs or ideas, let me know in issue.

Tomas
